### ISSUE TITLE
Failing test preventing build from passing

### ISSUE THREAD

**Issue by toddjordan** [ember-learn/ember-api-docs#177]
```
not ok 30 Chrome 57.0 - Switch Project: Can switch projects back and forth
    ---
        actual: >
            false
        expected: >
            true
        stack: >
                at Class.exception (http://localhost:7357/assets/test-support.js:5343:47)
                at adapterDispatch (http://localhost:7357/assets/vendor.js:50288:13)
                at dispatchError (http://localhost:7357/assets/vendor.js:28557:7)
                at invokeWithOnError (http://localhost:7357/assets/vendor.js:10921:7)
                at Queue.flush (http://localhost:7357/assets/vendor.js:10977:9)
                at DeferredActionQueues.flush (http://localhost:7357/assets/vendor.js:11101:15)
        message: >
            TypeError: Cannot read property 'split' of undefined
        Log: |
            { type: 'warn',
              text: '\'DEPRECATION: [DEPRECATED] Ember will stop passing arguments to component lifecycle hooks. Please change `<ember-api-docs@component:x-option::ember157775>#didReceiveAttrs` to stop taking arguments. [deprecation id: ember-views.lifecycle-hook-arguments] See http://emberjs.com/deprecations/v2.x/#toc_arguments-in-component-lifecycle-hooks for more details.\\n        at logDeprecationStackTrace (http://localhost:7357/assets/vendor.js:16384:19)\\n        at HANDLERS.(anonymous function) (http://localhost:7357/assets/vendor.js:16495:7)\\n        at raiseOnDeprecation (http://localhost:7357/assets/vendor.js:16414:12)\\n        at HANDLERS.(anonymous function) (http://localhost:7357/assets/vendor.js:16495:7)\\n        at invoke (http://localhost:7357/assets/vendor.js:16511:7)\\n        at deprecate (http://localhost:7357/assets/vendor.js:16479:32)\\n        at Object.deprecate (http://localhost:7357/assets/vendor.js:28321:37)\\n        at Class.exports.default._emberMetal.Mixin.create._Mixin$create.init (http://localhost:7357/assets/vendor.js:52410:17)\\n        at Class.superWrapper (http://localhost:7357/assets/vendor.js:51444:22)\'\n' },
           ... about a billion more of this deprecation (issue incoming)...
         { type: 'error',
              text: '\'TypeError: Cannot read property \\\'split\\\' of undefined\\n    at Class.<anonymous> (http://localhost:7357/assets/ember-api-docs.js:1872:45)\\n    at ComputedPropertyPrototype.get (http://localhost:7357/assets/vendor.js:27961:28)\\n    at Object.get (http://localhost:7357/assets/vendor.js:32954:19)\\n    at NestedPropertyReference.compute (http://localhost:7357/assets/vendor.js:25974:28)\\n    at NestedPropertyReference.value (http://localhost:7357/assets/vendor.js:25784:45)\\n    at NestedPropertyReference.compute (http://localhost:7357/assets/vendor.js:25957:42)\\n    at NestedPropertyReference.value (http://localhost:7357/assets/vendor.js:25784:45)\\n    at EvaluatedPositionalArgs.value (http://localhost:7357/assets/vendor.js:57811:36)\\n    at SimpleHelperReference.compute (http://localhost:7357/assets/vendor.js:26141:40)\\n    at SimpleHelperReference.value (http://localhost:7357/assets/vendor.js:25784:45)\'\n' }
            { type: 'error',
              text: '\'TypeError: Cannot read property \\\'split\\\' of undefined\\n    at Class.<anonymous> (http://localhost:7357/assets/ember-api-docs.js:1872:45)\\n    at ComputedPropertyPrototype.get (http://localhost:7357/assets/vendor.js:27961:28)\\n    at Object.get (http://localhost:7357/assets/vendor.js:32954:19)\\n    at NestedPropertyReference.compute (http://localhost:7357/assets/vendor.js:25974:28)\\n    at NestedPropertyReference.value (http://localhost:7357/assets/vendor.js:25784:45)\\n    at NestedPropertyReference.compute (http://localhost:7357/assets/vendor.js:25957:42)\\n    at NestedPropertyReference.value (http://localhost:7357/assets/vendor.js:25784:45)\\n    at EvaluatedPositionalArgs.value (http://localhost:7357/assets/vendor.js:57811:36)\\n    at SimpleHelperReference.compute (http://localhost:7357/assets/vendor.js:26141:40)\\n    at SimpleHelperReference.value (http://localhost:7357/assets/vendor.js:25784:45)\'\n' }
```

**Comment by sivakumar-kailasam** [comment]
This one is on account of CORS acting up weirdly in s3. I'm looking into this.

**Comment by sivakumar-kailasam** [comment]
Builds are good since we switched to my s3 account. I'll get the core team's s3 bucket setup with @acorncom soon.
