### ISSUE TITLE
Error template doesn't show up in some scenarios

### ISSUE THREAD

**Issue by sivakumar-kailasam** [ember-learn/ember-api-docs#186]
For both cases mentioned below we'll have to start by handling failures in the fetch that happens in the application adapter.

- In case there's a typo in the request, http://ead-sk.herokuapp.com/api-new/ember/2.12.0/namespaces/Embera, then fastboot gives us this old school error. 
<img width="960" alt="screenshot 2017-03-24 01 05 19" src="https://cloud.githubusercontent.com/assets/604117/24266749/f96d7b88-102d-11e7-9c3b-cea2c1e1563e.png">

- When user is offline & he switches to a url that isn't cached yet, the failed requests aren't handled.  It would be fancy to show a template that gives out this info about being offline & not being covered by service workers on this particular url. The [navigator api](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine) is probably useful here.
<img width="958" alt="screenshot 2017-03-24 01 06 22" src="https://cloud.githubusercontent.com/assets/604117/24266828/3170622a-102e-11e7-9e8e-d636b7d5ba04.png">

**Comment by toddjordan** [comment]
We should try to fix using route error substates, if fastboot supports.

**Comment by toddjordan** [comment]
Also, we need to support older patch releases, because people bookmark them.  @sivakumar-kailasam can we access previous patch data?

**Comment by sivakumar-kailasam** [comment]
@toddjordan we never showed actual patch release's docs on the UI via the version select. So I stopped generating docs for anything except the latest patch release. May be we can redirect to latest patch? If not I can generate older patch releases as well.

**Comment by acorncom** [comment]
I'm seeing this same issue when visiting http://emberjs.com/api-beta/ember/2.12.0/namespaces/Ember  Looks like it's related to not having `2.12.0` in the index

http://emberjs.com/api-beta/ember/2.12.2/namespaces/Ember works fine

**Comment by toddjordan** [comment]
@acorncom known issue we talked about in the meeting:  https://github.com/ember-learn/ember-api-docs/issues/179

**Comment by toddjordan** [comment]
I think https://github.com/ember-fastboot/fastboot/issues/134 is relevant to this issue

**Comment by toddjordan** [comment]
Tried the suggestion in  ember-fastboot/fastboot#134 and didn't affect the behavior

**Comment by toddjordan** [comment]
Here's the actual stacktrace:
```
Error: TransitionAborted
    at handleTransitionReject (/Users/jordanto/dev/ember-api-docs/tmp/funnel-output_path-pLhWexds.tmp/assets/vendor/ember/ember.debug.js:5137:1)
    at tryCatch (/Users/jordanto/dev/ember-api-docs/tmp/funnel-output_path-pLhWexds.tmp/assets/vendor/ember/ember.debug.js:50180:1)
    at invokeCallback (/Users/jordanto/dev/ember-api-docs/tmp/funnel-output_path-pLhWexds.tmp/assets/vendor/ember/ember.debug.js:50195:1)
    at publish (/Users/jordanto/dev/ember-api-docs/tmp/funnel-output_path-pLhWexds.tmp/assets/vendor/ember/ember.debug.js:50163:1)
    at publishRejection (/Users/jordanto/dev/ember-api-docs/tmp/funnel-output_path-pLhWexds.tmp/assets/vendor/ember/ember.debug.js:50098:1)
    at /Users/jordanto/dev/ember-api-docs/tmp/funnel-output_path-pLhWexds.tmp/assets/vendor/ember/ember.debug.js:40842:1
    at invokeWithOnError (/Users/jordanto/dev/ember-api-docs/tmp/funnel-output_path-pLhWexds.tmp/assets/vendor/ember/ember.debug.js:2197:1)
    at Object.flush (/Users/jordanto/dev/ember-api-docs/tmp/funnel-output_path-pLhWexds.tmp/assets/vendor/ember/ember.debug.js:2256:1)
    at Object.flush (/Users/jordanto/dev/ember-api-docs/tmp/funnel-output_path-pLhWexds.tmp/assets/vendor/ember/ember.debug.js:2380:1)
    at Object.end (/Users/jordanto/dev/ember-api-docs/tmp/funnel-output_path-pLhWexds.tmp/assets/vendor/ember/ember.debug.js:2450:1)
    at Timeout._onTimeout (/Users/jordanto/dev/ember-api-docs/tmp/funnel-output_path-pLhWexds.tmp/assets/vendor/ember/ember.debug.js:3016:1)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by toddjordan** [comment]
I actually think this is an oldie but goodie from fastboot, that we ran into before https://github.com/ember-fastboot/ember-cli-fastboot/issues/202

**Comment by toddjordan** [comment]
Alright, I have a fix.  Turns out is relates back to an old favorite: https://github.com/ember-fastboot/ember-cli-fastboot/issues/202

We are getting an error in our model hook, but transitions from model (or afterModel) are a problem in fastboot.  Therefore I'm now saving information about the error that happens in the model hook and doing the transition in the redirect hook.
