### ISSUE TITLE
API Docs are not working in IE 11

### ISSUE THREAD

**Issue by mhenley-uk** [ember-learn/ember-api-docs#304]
Whilst accessing the Ember API docs via IE 11 (Edge, 10 and 9 compat modes) The API docs render with the expected information but then hits a TypeError captured below and the contents disappear.

**URL**
https://emberjs.com/api/ember/2.14/namespaces/Ember

**ScreenShot**
https://pasteboard.co/GCI61GA.png

**Console Error**
```Error while processing route: project-version.namespaces.namespace.index Object doesn't support property or method 'includes' TypeError: Object doesn't support property or method 'includes'
   at Anonymous function (https://ember-api-docs-herokuapp-com.global.ssl.fastly.net/assets/ember-api-docs-1a5ede6c56b75b85acf3ff4a2633688b.js:248:364)
   at getFullVersion (https://ember-api-docs-herokuapp-com.global.ssl.fastly.net/assets/ember-api-docs-1a5ede6c56b75b85acf3ff4a2633688b.js:248:298)
   at Anonymous function (https://ember-api-docs-herokuapp-com.global.ssl.fastly.net/assets/ember-api-docs-1a5ede6c56b75b85acf3ff4a2633688b.js:191:8)
   at r (https://ember-api-docs-herokuapp-com.global.ssl.fastly.net/assets/vendor-d5ab98c19f5605dcf7ece61ed2610576.js:27:51)
   at Anonymous function (https://ember-api-docs-herokuapp-com.global.ssl.fastly.net/assets/vendor-d5ab98c19f5605dcf7ece61ed2610576.js:48:1)
   at e[t] (https://ember-api-docs-herokuapp-com.global.ssl.fastly.net/assets/vendor-d5ab98c19f5605dcf7ece61ed2610576.

TypeError: Object doesn't support property or method 'includes'
   at Anonymous function (https://ember-api-docs-herokuapp-com.global.ssl.fastly.net/assets/ember-api-docs-1a5ede6c56b75b85acf3ff4a2633688b.js:248:364)
   at getFullVersion (https://ember-api-docs-herokuapp-com.global.ssl.fastly.net/assets/ember-api-docs-1a5ede6c56b75b85acf3ff4a2633688b.js:248:298)
   at Anonymous function (https://ember-api-docs-herokuapp-com.global.ssl.fastly.net/assets/ember-api-docs-1a5ede6c56b75b85acf3ff4a2633688b.js:191:8)
   at r (https://ember-api-docs-herokuapp-com.global.ssl.fastly.net/assets/vendor-d5ab98c19f5605dcf7ece61ed2610576.js:27:51)
   at Anonymous function (https://ember-api-docs-herokuapp-com.global.ssl.fastly.net/assets/vendor-d5ab98c19f5605dcf7ece61ed2610576.js:48:1)
   at e[t] (https://ember-api-docs-herokuapp-com.global.ssl.fastly.net/assets/vendor-d5ab98c19f5605dcf7ece61ed2610576.js:27:245)
   at n (https://ember-api-docs-herokuapp-com.global.ssl.fastly.net/assets/ember-api-docs-1a5ede6c56b75b85acf3ff4a2

TypeError: Object doesn't support property or method 'includes'
   at Anonymous function (https://ember-api-docs-herokuapp-com.global.ssl.fastly.net/assets/ember-api-docs-1a5ede6c56b75b85acf3ff4a2633688b.js:10:80)
   at r (https://ember-api-docs-herokuapp-com.global.ssl.fastly.net/assets/vendor-d5ab98c19f5605dcf7ece61ed2610576.js:27:51)
   at Anonymous function (https://ember-api-docs-herokuapp-com.global.ssl.fastly.net/assets/vendor-d5ab98c19f5605dcf7ece61ed2610576.js:48:1)
   at e[t] (https://ember-api-docs-herokuapp-com.global.ssl.fastly.net/assets/vendor-d5ab98c19f5605dcf7ece61ed2610576.js:27:245)
   at n (https://ember-api-docs-herokuapp-com.global.ssl.fastly.net/assets/ember-api-docs-1a5ede6c56b75b85acf3ff4a2633688b.js:3:54)
   at Anonymous function (https://ember-api-docs-herokuapp-com.global.ssl.fastly.net/assets/ember-api-docs-1a5ede6c56b75b85acf3ff4a2633688b.js:4:6)
   at S (https://ember-api-docs-herokuapp-com.global.ssl.fastly.net/assets/vendor-d5ab98c19f5605dcf7ece61ed2610576.js:3223:5)
   at F (
```

**Extra Details**
- Windows 7
- IE 11.0.9600.18449

**Comment by acorncom** [comment]
Looks like this is related to `Array.includes()` usage that IE doesn't support (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes#Browser_compatibility)

Usage is here.  We should be able to move these to `Ember.A()` usage and have those errors go away ...
```
app/adapters/application.js:    if (['namespace', 'class', 'module'].includes(modelName)) {
app/mixins/filter-params.js:          let enabled = filters.includes(filter);
app/services/meta-store.js:    return availProjVersions.filter(v => v.includes(compactProjVersion))[0];
```

@mhenley-uk Do you have time to check/fix this in IE11?  I don't regularly use it, so it'll take a bit on my end to get that fixed ...

**Comment by mhenley-uk** [comment]
@acorncom I've just a quick look this morning, will try to spend a little more on it later. By the looks of things its down to IE not supporting includes on Strings.

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/includes

Its where `v` in the loop is a string, Chrome, Firefox and Edge support but IE has none.
https://github.com/ember-learn/ember-api-docs/blob/master/app/services/meta-store.js#L38

I'm assuming we'd want to keep the code as is and attempt to find an appropriate shim rather than putting in something that would become out of date and not fit with ES6. Maybe a babel polyfill or one specifically for String.prototype.includes()

I actually don't use IE either (who does...), we just have to ensure we can support them through our ember applications and found the issue whilst debugging an issue with ember-anchor on IE and Firefox.
