### ISSUE TITLE
Cannot navigate left nav links in IE11

### ISSUE THREAD

**Issue by rwjblue** [ember-learn/ember-api-docs#482]
As reported [in the discuss forum](https://discuss.emberjs.com/t/multiple-errors-when-viewing-emberjs-com-in-ie11-on-windows-7/14460/5?u=rwjblue) the following either need to be refactored or we need to include a polyfill (since `Array.prototype.includes` is not available):

https://github.com/ember-learn/ember-api-docs/blob/4721d6747b04eaada459c5ea6c6737790273f340/app/adapters/application.js#L25

https://github.com/ember-learn/ember-api-docs/blob/7943dba1683b30b89249ae11118cae93aad79f1b/app/mixins/filter-params.js#L35

**Comment by toddjordan** [comment]
odd thing is we already have a polyfill https://github.com/ember-learn/ember-api-docs/blob/master/app/initializers/add-string-includes-polyfill.js

I did introduce a pr that removed includes usage in #478, but I dropped it thinking #479 would fix it without dropping it.  I could have been mistaken there.

**Comment by MartinMalinda** [comment]
That's a polyfill for String.includes - last time someone tested on IE11 that was the missing one - https://github.com/ember-learn/ember-api-docs/issues/304#issuecomment-318614218

But it seems like IE11 does not even have Array.includes so it probably needs to be added as well. Or just wrap those arrays in `A()`.

**Comment by toddjordan** [comment]
So we've fixed the includes issue (by just using a IE11-friendly alternative), but it seems we still have general IE 11 issues so keeping this open.

Clicking on any link in the left nav Produces the following and doesn't render the page:
![image](https://user-images.githubusercontent.com/3609063/38623073-bca7daa4-3d72-11e8-970e-8519f36cd4de.png)

(note: I'm trying this in browserstack)

stack: 
stack	"Error: Invalid argument.\n   at t.prototype.update (https://ember-api-docs-frontend.global.ssl.fastly.net/assets/vendor-edda4cb740c888e1d9cdbda932b04712.js:1727:1)\n   at t.prototype.evaluate (https://ember-api-docs-frontend.global.ssl.fastly.net/assets/vendor-edda4cb740c888e1d9cdbda932b04712.js:1740:197)\n   at e.prototype.execute (https://ember-api-docs-frontend.global.ssl.fastly.net/assets/vendor-edda4cb740c888e1d9cdbda932b04712.js:1957:39)\n   at e.prototype.rerender (https://ember-api-docs-frontend.global.ssl.fastly.net/assets/vendor-edda4cb740c888e1d9cdbda932b04712.js:1983:1)\n   at a.render (https://ember-api-docs-frontend.global.ssl.fastly.net/assets/vendor-edda4cb740c888e1d9cdbda932b04712.js:2619:21)\n   at e.runInTransaction (https://ember-api-docs-frontend.global.ssl.fastly.net/assets/vendor-edda4cb740c888e1d9cdbda932b04712.js:2931:60)\n   at e.prototype._renderRoots (https://ember-api-docs-frontend.global.ssl.fastly.net/assets/vendor-edda4cb740c888e1d9cdbda932b04712.js:2634:141)\n   at e.prototype._renderRootsTransaction (https://ember-api-docs-frontend.global.ssl.fastly.net/assets/vendor-edda4cb740c888e1d9cdbda932b04712.js:2639:5)\n   at e.prototype._revalidate (https://ember-api-docs-frontend.global.ssl.fastly.net/assets/vendor-edda4cb740c888e1d9cdbda932b04712.js:2641:332)\n   at e.prototype.invoke (https://ember-api-docs-frontend.global.ssl.fastly.net/assets/vendor-edda4cb740c888e1d9cdbda932b04712.js:2079:156)"
