### ISSUE TITLE
Diagnose API docs downtime

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-api-docs#670]
<img width="1196" alt="Screen Shot 2020-02-20 at 6 03 50 PM" src="https://user-images.githubusercontent.com/16627268/74988290-786cef80-540b-11ea-88c9-daffabd8d8f6.png">

Checking...
- [x] heroku provider status is green https://status.heroku.com/
- [ ] AWS status
- [x] heroku logs - see below
- [x] recent deploys - last merge was 9 days ago
- [ ] docs bucket

Heroku logs - 503 app crashed. Get logs with `heroku logs -a ember-api-docs-subdomain-setup -n 1000`

`desc="App crashed" method=GET path="/ember/release/classes/Ember.DataAdapter/properties"``

**Comment by jenweber** [comment]
It resolved on its own. These periodic stack traces might be worth looking into though:

```
2020-02-20T23:16:55.057155+00:00 app[web.1]: Error while processing route: class Only absolute URLs are supported TypeError: Only absolute URLs are supported
2020-02-20T23:16:55.057172+00:00 app[web.1]: at getNodeRequestOptions (/app/tmp/deploy-dist/node_modules/node-fetch/lib/index.js:1293:9)
2020-02-20T23:16:55.057173+00:00 app[web.1]: at /app/tmp/deploy-dist/node_modules/node-fetch/lib/index.js:1393:19
2020-02-20T23:16:55.057174+00:00 app[web.1]: at new Promise (<anonymous>)
2020-02-20T23:16:55.057174+00:00 app[web.1]: at fetch (/app/tmp/deploy-dist/node_modules/node-fetch/lib/index.js:1390:9)
2020-02-20T23:16:55.057174+00:00 app[web.1]: at abortableFetch (/app/node_modules/abortcontroller-polyfill/dist/cjs-ponyfill.js:436:12)
2020-02-20T23:16:55.057175+00:00 app[web.1]: at n.fetch (/app/tmp/deploy-dist/assets/ember-api-docs-25572d828074f773af58544e93b72153.js:247:94)
2020-02-20T23:16:55.057175+00:00 app[web.1]: at n.model (/app/tmp/deploy-dist/assets/ember-api-docs-25572d828074f773af58544e93b72153.js:147:34)
2020-02-20T23:16:55.057176+00:00 app[web.1]: at n.deserialize (/app/tmp/deploy-dist/assets/vendor-8829232c84130863b1988edd68288c26.js:3339:121)
2020-02-20T23:16:55.057176+00:00 app[web.1]: at /app/tmp/deploy-dist/assets/vendor-8829232c84130863b1988edd68288c26.js:3963:88
2020-02-20T23:16:55.057177+00:00 app[web.1]: at n.e.runSharedModelHook (/app/tmp/deploy-dist/assets/vendor-8829232c84130863b1988edd68288c26.js:3963:122)
2020-02-20T23:16:55.080670+00:00 app[web.1]: 2020-02-20T23:16:55.079Z 200 OK /ember/release/classes/Route
2020-02-20T23:16:55.177603+00:00 app[web.1]: 2020-02-20T23:16:55.176Z 200 OK /classes/Ember.NativeArray.html
2020-02-20T23:16:55.247883+00:00 app[web.1]: Error while processing route: data-class Only absolute URLs are supported TypeError: Only absolute URLs are supported
2020-02-20T23:16:55.247885+00:00 app[web.1]: at getNodeRequestOptions (/app/tmp/deploy-dist/node_modules/node-fetch/lib/index.js:1293:9)
2020-02-20T23:16:55.247886+00:00 app[web.1]: at /app/tmp/deploy-dist/node_modules/node-fetch/lib/index.js:1393:19
2020-02-20T23:16:55.247886+00:00 app[web.1]: at new Promise (<anonymous>)
2020-02-20T23:16:55.247887+00:00 app[web.1]: at fetch (/app/tmp/deploy-dist/node_modules/node-fetch/lib/index.js:1390:9)
2020-02-20T23:16:55.247887+00:00 app[web.1]: at abortableFetch (/app/node_modules/abortcontroller-polyfill/dist/cjs-ponyfill.js:436:12)
2020-02-20T23:16:55.247888+00:00 app[web.1]: at n.fetch (/app/tmp/deploy-dist/assets/ember-api-docs-25572d828074f773af58544e93b72153.js:247:94)
2020-02-20T23:16:55.247888+00:00 app[web.1]: at n.model (/app/tmp/deploy-dist/assets/ember-api-docs-25572d828074f773af58544e93b72153.js:150:34)
2020-02-20T23:16:55.247888+00:00 app[web.1]: at n.deserialize (/app/tmp/deploy-dist/assets/vendor-8829232c84130863b1988edd68288c26.js:3339:121)
2020-02-20T23:16:55.247889+00:00 app[web.1]: at /app/tmp/deploy-dist/assets/vendor-8829232c84130863b1988edd68288c26.js:3963:88
2020-02-20T23:16:55.247889+00:00 app[web.1]: at n.e.runSharedModelHook (/app/tmp/deploy-dist/assets/vendor-8829232c84130863b1988edd68288c26.js:3963:122)
2020-02-20T23:16:55.257286+00:00 app[web.1]: 2020-02-20T23:16:55.257Z 200 OK /data/classes/DS.Model.html
```

**Comment by bertdeblock** [comment]
Hi @jenweber, I noticed today that navigating directly to https://api.emberjs.com/ember/release results in the same error screen. I'm located in Belgium.

**Comment by sivakumar-kailasam** [comment]
Our systems show that there was a 2min downtime. Did you notice it being
longer?

Regards,
Siva

**Comment by cbliard** [comment]
At 11:05 (GMT+01) it was not working

**Comment by bertdeblock** [comment]
@sivakumar-kailasam, yes it was definitely longer than 2 minutes for me. It's back up now though 👍.

**Comment by sivakumar-kailasam** [comment]
Seems close to what's reported at http://status.emberjs.com/5540057

Regards,
Siva
