### ISSUE TITLE
Update to a more recent version of fastboot

### ISSUE THREAD

**Issue by Gaurav0** [ember-learn/ember-api-docs#68]
Currently using 0.6

**Comment by Gaurav0** [comment]
So I tried to this in branch https://github.com/Gaurav0/ember-api-docs/tree/fastboot
and got:

2016-11-16T00:35:58.418Z 500 Unknown Error: Error: TransitionAborted
    at handleReject (/Users/gmunjal/dev/emberjs/ember-api-docs/dist/fastboot/vendor.js:14143:17)
    at tryCatch (/Users/gmunjal/dev/emberjs/ember-api-docs/dist/fastboot/vendor.js:61081:14)
    at invokeCallback (/Users/gmunjal/dev/emberjs/ember-api-docs/dist/fastboot/vendor.js:61096:15)
    at publish (/Users/gmunjal/dev/emberjs/ember-api-docs/dist/fastboot/vendor.js:61064:9)
    at publishRejection (/Users/gmunjal/dev/emberjs/ember-api-docs/dist/fastboot/vendor.js:60999:5)
    at /Users/gmunjal/dev/emberjs/ember-api-docs/dist/fastboot/vendor.js:50544:16
    at Queue.invokeWithOnError (/Users/gmunjal/dev/emberjs/ember-api-docs/dist/fastboot/vendor.js:11126:18)
    at Object.Queue.flush (/Users/gmunjal/dev/emberjs/ember-api-docs/dist/fastboot/vendor.js:11181:11)
    at Object.DeferredActionQueues.flush (/Users/gmunjal/dev/emberjs/ember-api-docs/dist/fastboot/vendor.js:10989:17)
    at Object.Backburner.end (/Users/gmunjal/dev/emberjs/ember-api-docs/dist/fastboot/vendor.js:10303:25)
    at null._onTimeout (/Users/gmunjal/dev/emberjs/ember-api-docs/dist/fastboot/vendor.js:10869:18)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by Gaurav0** [comment]
Looks like https://github.com/ember-fastboot/ember-cli-fastboot/issues/202 . Guess I'm blocked.
